### ISSUE TITLE
Ch 4 Test Spectrum Diagram PNG Rendering

### ISSUE THREAD

**Issue by xtaje** [cosmicpython/book#212]
![image](https://user-images.githubusercontent.com/5151439/72376442-cda63a80-36c2-11ea-9dc3-6f54cad11c90.png)

Left side of pic is what I'm seeing in master, right side is what I get when I `make diagrams` locally.  Not sure if there's some issue with the build system or this can just be safely ignored until the final print.

**Comment by hjwp** [comment]
i can't see any difference between the images themselves, is the discrepancy the `<pre>` source block underneath, on the left-hand side? 

if so that's because we keep the actual image and the image source inline with each other in our asciidoc sources, and i use some css hackery to be able to hiding then inline source in local and pdf renders.  but github's previews don't respect my css...

**Comment by hjwp** [comment]
https://github.com/cosmicpython/book/blob/master/theme/asciidoctor.local.css#L6

**Comment by xtaje** [comment]
I updated the image to point out the missing the missing text.  I don't think it's a CSS render thing because the raw png on master doesn't have the labels.

**Comment by hjwp** [comment]
gotcha.
