### ISSUE TITLE
With regards to Django here's a counterpoint argument abt not using the repository pattern

### ISSUE THREAD

**Issue by simkimsia** [cosmicpython/book#300]
https://www.b-list.org/weblog/2020/mar/16/no-service/

this article calls it services layer

Putting it here first especially for the more Django inclined readers like me. Not sure whether I agree or disagree and why

**Comment by simkimsia** [comment]
Sorry i think i should not treat the issues as forum posts. I will close this

**Comment by hjwp** [comment]
yes i read that at the time.  I think the follow-up post is really interesting:

https://www.b-list.org/weblog/2020/mar/23/still-no-service/

I took three main things away from it:

1. he calls out a pub/sub message bus as one possible good solution for managing complexity

2. he says that if you really want to decouple your ORM from your application, don't use django's ORM because it's based on activerecord, try sqlalchemy instead

3. he says he's given up on the idea of trying to isolate your business logic from your database, because essentially the database is too important a component of the typical web app, so your mocks get too complicated.  here i think repository and unit of work patterns genuinely do solve the problems he's hinting at, but you do have to go back and address problem 2 first...
