### ISSUE TITLE
[Question] SqlAlchemy complete decoupling - is it possible?

### ISSUE THREAD

**Issue by nikoladsp** [cosmicpython/book#327]
Hi,
I found this material of great value since I recognized some of the troubles we introduced a long time ago when setting up initial model.

There are couple of dilemmas we are now facing. Even if we set mapping of a (business) model (standard Python dataclass) to a SqlAlchemy Table (ORM) model, SqlAlchemy is going to apply it's own "magic" and append **_sa_instance_state** (object property) and **_sa_class_manager** (class property). Even those 2 (and potentially more) are hidden (protected) I really don't like the idea of passing SqlAlchemy related stuff in business model; since this is why I do the refactor in first place - to decouple business from ORM model.

So my question is - is there a clean way to completely remove SqlAlchemy from my business model? First thing comes to my mind is to translate query results to dict or named tuple and populate dataclass.

Second question is related: how to handle partial updates: is this something I have to code in? Or it can be handled by SqlAlchemy (ORM in general) - taken that business model is decoupled from ORM model.

Many thanks.

Best regards

**Comment by hjwp** [comment]
Hi there, I'll repeat my answer from the other thread in case it helps anyone -- 

as always it's a tradeoff.  Yes, in order to work, SQLAlchemy has to get its claws pretty deep into your objects, so they are not "truly" decoupled.  On the other hand, an ORM does a lot of the heavy lifting for getting objects in and out of database columns.

The alternative is not to use an ORM at all, which I've enjoyed doing on the last few projects.   You have to write a lot of your own SQL tho!  Check out the exercise for the reader here, so you can get a feel for the tradeoff http://www.cosmicpython.com/book/chapter_02_repository.html#api_endpoint_with_repo

**Comment by nikoladsp** [comment]
Thank you. 

Not using ORM looks like a good idea. I mean, SQLAlchemy is great, but I don't want this kind of pollution in my business model dataclass objects. Alternative is maybe to create some mapping between ORM and dataclasses manually, but in that case I don't see a need for ORM.

Maybe this should be emphasised somewhere in the book as my hopes get quite high for a moment.

Best regards

**Comment by Bryant-Yang** [comment]
I used to look forward some 'magic' to do this, but may be it's not necessary.

All business logic in domain model or service may look like pure OOP, with or without sqlalchemy, the change should stay only in repositories. 

Without a mature ORM, I think it still need some extra "pollution" to map the pure domain model to database table (if relational database used). 

And case may be more complex to make aggregation (similar to UML class diagram combination) if DIY the model - table mapping.
