### ISSUE TITLE
What comes after the allocation example? Or: how to modularize the event-driven architecture?

### ISSUE THREAD

**Issue by jqhoogland** [cosmicpython/book#335]
Let's take the example from the book (so we're tracking allocations of stock). Suppose we want to add the next module — maybe authentication and authorization? 

If I create a new module called `auth` ([next to `allocation`](https://github.com/cosmicpython/code/tree/master/src)) with parallel internal structure, how can I keep the dependencies between it and the existing `allocation` module clean?

At its simplest, we might want to add an "owner" to the `OrderLine` and access `OrderLine` by owners. 

We'll have to add a foreign key constraint in the [`orms`](https://github.com/cosmicpython/code/blob/master/src/allocation/adapters/orm.py) so there's a dependency that jumps between services. And I imagine we'll want an aggregator for user-specific bookings. If we put this in the new `auth` module, then it'll have a dependency to the existing `model.OrderLine` (in the opposite direction). 

That's not so bad yet, but with a few more modules it seems like it'll be easier and easier to slip back to mud ball. Any suggestions for managing dependencies between modules?

**Comment by hjwp** [comment]
I think auth is a tricky example, because it's a classic case of "cross-cutting concerns" - like logging, or metrics, or audit logs maybe.  they often call for slightly special treatment.

with that said --

in general, the "classic" way of keeping things modular in DDD is by using bounded contexts.  bounded contexts are supposed to be as independent from each other as possible, and you might have specific layers for translating from one to the other.  and at a lower level, you would avoid having foreign keys that cross bounded contexts.  have a peek at the content around "anticorruption layer" in the blue book, if you can get access to it?

so either you figure out a way to do all your auth stuff upstream of allocation, such that all you need to pass down is a user id.  or if you really need more info about owners for allocation to work, then maybe owners need to be part of your allocation's bounded context, and you need to have a think about what the aggregates are and who will own the consistency boundaries.  idk, maybe it becomes Owner.allocate(orderline) instead of Product.allocate(orderline).

well, that's my advice for what it's worth!  it comes from what i'm at pains to stress is quite limited experience, i'm afraid :sweat_smile: .  i'd encourage you to read up on things in another DDD book, and/or go and ask questions in the [DDD-CQRS-ES slack](https://github.com/ddd-cqrs-es/slack-community) which is a very friendly bunch of people who are always up for talking about things like this...

**Comment by jqhoogland** [comment]
Thank you so much Harry! This is already a great push in the right direction (I'm already reading through the blue book and will check out the slack.)
