### ISSUE TITLE
Can we use async await

### ISSUE THREAD

**Issue by Didza** [cosmicpython/book#342]
Amazing work, Can we use async await with this for external calls e.g the database? If not why not, if we can what are the reasons for not adding this? Thank you!!!

**Comment by suspiciousRaccoon** [comment]
[This](https://github.com/cosmicpython/code/issues/68) repo uses fastapi. Might be what you're looking for.

**Comment by hjwp** [comment]
async/await can actually be a really nice way to separate out code with side-effects from your domain model, which should be side-effect free. 

in terms of the patterns in the book, it would tend to mean that anything involving a repostiory, and anything involving the UoW, becomes async.  that's unfortunate because, if you want to test everything at the service layer, all your tests become async tests, which are a bit slow.  so either you accept that as a cost/compromise, or you do more non-async/unit testing at the lower/domain layer.  or maybe there's a clever way to avoid async in the service layer / repository / uow!  that last is an open question, for me.

another way of thinking about it is that async can make it really visible, in code, as to how well you're doing with the "functional core imperative shell" pattern.  so i think it can be really good!

**Comment by Didza** [comment]
Blocking calls to external resources create an overhead where the thread is blocked from serving other requests, async/await can lead to performance improvements in these scenarios. It allows for non-blocking I/O operations, which is particularly beneficial in web servers and applications dealing with high I/O workloads.
